### ISSUE TITLE
Incorrect Model Instantiation Method in Quickstart Guide

### ISSUE THREAD

**Issue by TimoCuijpers** [weapnl/js-junction#11]
It appears that the model instantiation and method call are currently documented as User.index(), which may not correctly reflect the intended usage pattern of the model.

To align with standard object-oriented programming practices and our project's codebase conventions, I suggest updating the documentation to reflect one of the following corrected forms:

For static method access: user.index()
For instance method access: new User().index()
This adjustment will ensure that new users and contributors can quickly understand and correctly implement the model instantiation process without confusion.

Thank you for considering this update to improve our documentation's accuracy and usability.

Best regards,

Timo Cuijpers

**Comment by robinvda** [comment]
Can you make a pr for this?

**Comment by TimoCuijpers** [comment]
Sure!

**Comment by TimoCuijpers** [comment]
https://github.com/weapnl/js-junction/pull/20

**Comment by robinvda** [comment]
Merged
