### ISSUE TITLE
Feature request: Customizable Response Type for Actions

### ISSUE THREAD

**Issue by TimoCuijpers** [weapnl/js-junction#12]
Currently, the framework's actions are designed to return responses in JSON format. However, for enhanced flexibility and to accommodate different use cases, it would be beneficial to introduce the capability to specify the response type of an action. Specifically, there are scenarios where an action's response is more appropriately represented as a Blob type, rather than a JSON object. This feature would provide developers with the flexibility to tailor the response format to their specific needs, enhancing the framework's usability and applicability across a wider range of applications.

Could the development team consider implementing an option or method that allows for the customization of response types for actions? If so, would there be any implications or requirements to be aware of, ensuring it aligns with the framework's design principles and performance expectations?

Best regards,
Timo Cuijpers

**Comment by robinvda** [comment]
An action should already be able to return any type of response you want (if i'm correct). What change would you like to see here?

**Comment by TimoCuijpers** [comment]
When I want to return a blob object instead of a json object from my Laravel controller, Junction will automatically convert it into a json object if I'm correct. In this case, Junction makes it unavailable to directly download a blob response given from the Laravel controller. This would be useful if there is a file generated in the controller.

To be honest, this can be a misunderstanding from me. 

In this screenshot I show the Content-type which is a application/json object.
<img width="286" alt="image" src="https://github.com/weapnl/js-junction/assets/82875662/cfd68f48-8f3c-4fb5-84b6-b3f9b3176aec">

###### As mentioned in the description of the issue, I can understand if this feature doesn't fit the package's purposes.

**Comment by robinvda** [comment]
We've merged a change which should fix this issue as well, see https://github.com/weapnl/js-junction/pull/21. It allows you to set config values, so you can set the type.

**Comment by TimoCuijpers** [comment]
Thank you! Awesome
