### ISSUE TITLE
Request cancelling

### ISSUE THREAD

**Issue by jobjen02** [weapnl/js-junction#17]
Er moeten extra callbacks komen om het annuleren van requests goed op te vangen. @robinvda en ik hebben als idee om een `onBefore` en `onAfter` callback toe te voegen aan deze package. De `onAfter` zal dan niet worden aangeroepen als een request wordt geannuleerd.

Dit zorgt er dan voor dat als je bijvoorbeeld een `loading` prop op `true` zet voor het request deze niet meteen op `false` wordt gezet na het request, als deze wordt geannuleerd. Dit zorgt er namelijk voor dat de loading state niet meer klopt, aangezien het nieuwe request dan wel al bezig is.

**Comment by robinvda** [comment]
Discussie punt: Moet `onBefore` aangeroepen als het request een voorgaand request cancelled?
Omdat `onBefore` anders geen toegevoegde waarde heeft zou ik zeggen van niet. Evt een 2e parameter (boolean) toevoegen waarmee je dit kunt overriden?

Het is ook consistent. `onAfter` wordt niet aangeroepen bij een cancel. `onBefore` wordt ook niet aangeroepen bij een cancel.
